# Artificial Neural Network

### Importo Librerias

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## PARTE 1: Proceso de datos

### Importo datos

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

### Creo Encoding para data categorica

Encoding para "Gender"

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

Encoding para "Geography"

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Separo data en training y testing 

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Escalo todo los datos

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## PARTE 2: Construccion de ANN

### Inicializo

In [15]:
ann = tf.keras.models.Sequential()

### Agrego una primera capa

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Agrego una segunda capa

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Agrego capa de salida

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## PARTE 3: Entreno a la ANN

### Compilo la ANN

In [19]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Entreno la ANN con el set de training

In [20]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 884us/step - loss: 0.5696 - accuracy: 0.7660
Epoch 2/100
250/250 [==============================] - 0s 888us/step - loss: 0.4794 - accuracy: 0.7959
Epoch 3/100
250/250 [==============================] - 0s 895us/step - loss: 0.4482 - accuracy: 0.8005
Epoch 4/100
250/250 [==============================] - 0s 964us/step - loss: 0.4338 - accuracy: 0.8069
Epoch 5/100
250/250 [==============================] - 0s 875us/step - loss: 0.4254 - accuracy: 0.8135
Epoch 6/100
250/250 [==============================] - 0s 896us/step - loss: 0.4199 - accuracy: 0.8166
Epoch 7/100
250/250 [==============================] - 0s 883us/step - loss: 0.4158 - accuracy: 0.8198
Epoch 8/100
250/250 [==============================] - 0s 904us/step - loss: 0.4118 - accuracy: 0.8215
Epoch 9/100
250/250 [==============================] - 0s 873us/step - loss: 0.4087 - accuracy: 0.8253
Epoch 10/100
250/250 [==============================] - 0s 871us/step - l

## Parte 4: Hago las predicciones del modelo

### Pruebo una prediccion individual

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000


**Solution**

In [21]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


### Predigo los resultados del Testing Set

In [23]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Hago matriz de Confusion

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1504   91]
 [ 183  222]]


0.863